# vim: set filetype=python:

env = Environment()
env.Append(CPPPATH='#/include')

env.VariantDir('obj', 'src')
env.SConscript('obj/SConscript')

t = env.Program('main', Glob('obj/*.o') , LIBS=['m'])

env.NoClean('main')
env.Clean(t, Glob('obj/*'))
